from enum import EnumMeta, IntEnum, auto


class MetaEnum(EnumMeta):
    def __contains__(cls, item):
        return (item in cls.__members__) or (item in cls._value2member_map_)
    
class RGBMode(IntEnum, metaclass = MetaEnum):
    off = 0
    on = 1
    cycling = 3
    breathing = 10

#https://github.com/clovervidia/G403HID/blob/master/G403HID/SimpleMapping.cs
#with correction
class MouseButton(IntEnum, metaclass = MetaEnum):
    left_button = 0x80010001
    right_button = 0x80010002
    middle_button = 0x80010004
    backward_button = 0x80010008
    forward_button = 0x80010010
    media_nexttrack = 0x800300B5
    media_prevtrack = 0x800300B6
    media_stop = 0x800300B7
    media_playpause = 0x800300CD
    media_volmute = 0x800300E2
    media_volup = 0x800300E9
    media_voldown = 0x800300EA
    display_brightup = 0x8003006F
    display_brightdown = 0x80030070
    no_action = 0x9000FF00
    wheel_left = 0x9001FF00
    wheel_right = 0x9002FF00
    next_dpi = 0x9003FF00
    previous_dpi = 0x9004FF00
    cycle_dpi = 0x9005FF00
    default_dpi = 0x9006FF00
    dpi_shift = 0x9007FF00
    next_profile = 0x9008FF00
    previous_profile = 0x9009FF00
    cycle_profile = 0x900AFF00
    g_shift = 0x900BFF00
    battery_indicator = 0x900CFF00
    enable_profile = 0x900DFF00
    performance_mode = 0x900EFF00
    host_button = 0x900FFF00
    scroll_down = 0x9010FF00
    scroll_up = 0x9011FF00
    no_button = 0xFFFFFFFF

#https://github.com/clovervidia/G403HID/blob/master/G403HID/ModifierKeypressMapping.cs
#USB HID keyboard code.
class KeyCode(IntEnum, metaclass = MetaEnum):
    a  = 4
    b = auto()
    c = auto()
    d = auto()
    e = auto()
    f = auto()
    g = auto()
    h = auto()
    i = auto()
    j = auto()
    k = auto()
    l = auto()
    m = auto()
    n = auto()
    o = auto()
    p = auto()
    q = auto()
    r = auto()
    s = auto()
    t = auto()
    u = auto()
    v = auto()
    w = auto()
    x = auto()
    y = auto()
    z = auto()
    num1 = auto()
    num2 = auto()
    num3 = auto()
    num4 = auto()
    num5 = auto()
    num6 = auto()
    num7 = auto()
    num8 = auto()
    num9 = auto()
    num0 = auto()
    enter = auto()
    escape = auto()
    backspace = auto()
    tab = auto()
    space = auto()
    minus = auto()
    equal = auto()
    leftbracket = auto()
    rightbracket = auto()
    backslash = auto()
    nonuspound = auto()
    semicolon = auto()
    quote = auto()
    graveaccent = auto()
    comma = auto()
    period = auto()
    slash = auto()
    capslock = auto()
    f1 = auto()
    f2 = auto()
    f3 = auto()
    f4 = auto()
    f5 = auto()
    f6 = auto()
    f7 = auto()
    f8 = auto()
    f9 = auto()
    f10 = auto()
    f11 = auto()
    f12 = auto()
    printscreen = auto()
    scrolllock = auto()
    pause = auto()
    insert = auto()
    home = auto()
    pageup = auto()
    delete = auto()
    end = auto()
    pagedown = auto()
    rightarrow = auto()
    leftarrow = auto()
    downarrow = auto()
    uparrow = auto()
    numlock = auto()
    keypadslash = auto()
    keypadasterisk = auto()
    keypadminus = auto()
    keypadplus = auto()
    keypadenter = auto()
    keypad1 = auto()
    keypad2 = auto()
    keypad3 = auto()
    keypad4 = auto()
    keypad5 = auto()
    keypad6 = auto()
    keypad7 = auto()
    keypad8 = auto()
    keypad9 = auto()
    keypad0 = auto()
    keypadperiod = auto()
    nonusbackslash = auto()
    menu = auto()
    power = auto()
    keypad_equals = auto()
    f13 = auto()
    f14 = auto()
    f15 = auto()
    f16 = auto()
    f17 = auto()
    f18 = auto()
    f19 = auto()
    f20 = auto()
    f21 = auto()
    f22 = auto()
    f23 = auto()
    f24 = auto()
    keypadcomma  = 133
    international1  = 135
    international2 = auto()
    international3 = auto()
    international4 = auto()
    international5 = auto()
    international6 = auto()
    language1  = 144
    language2 = auto()
    language3 = auto()
    language4 = auto()
    language5 = auto()
    lctrl = 224
    lshift = auto()
    lalt = auto()
    lgui = auto()
    rctrl = auto()
    rshift = auto()
    ralt = auto()
    rgui = auto()

class Modifier(IntEnum, metaclass = MetaEnum):
    lctrl = 0x100
    lshift = 0x200
    lalt = 0x400
    lgui = 0x800
    rctrl = 0x1000
    rshift = 0x2000
    ralt = 0x4000
    rgui = 0x8000

class MacroControl(IntEnum, metaclass = MetaEnum):
    no_op = 0x0
    pause = 0x1
    repeat = 0x2
    loop = 0x3
    wheel = 0x20
    wheelh = 0x21
    sleep = 0x40
    btn_down = 0x41
    btn_up = 0x42
    key_down = 0x43
    key_up = 0x44
    next_page = 0x60
    move = 0x61
    macro_end = 0xff

class USBReceiver(IntEnum, metaclass = MetaEnum):
    unifying1 = 0xC52B
    unifying2 = 0xC532
    #untested...
    # lightspeed1 = 0xC539
    # lightspeed2 = 0xC53F
    # lightspeed3 = 0xC547
    # powerplay = 0xC53A
